metadata name = 'Azure Naming module'
metadata description = 'Module to maintain a consistent naming of Azure resources.'

@export()
var regionAbbreviations = {
  australiacentral: 'acl'
  australiacentral2: 'acl2'
  australiaeast: 'ae'
  australiasoutheast: 'ase'
  austriaeast: 'aue'
  belgiumcentral: 'bec'
  brazilsouth: 'brs'
  brazilsoutheast: 'bse'
  canadacentral: 'cnc'
  canadaeast: 'cne'
  centralindia: 'inc'
  centralus: 'cus'
  centraluseuap: 'ccy'
  chilecentral: 'clc'
  denmarkeast: 'dke'
  eastasia: 'ea'
  eastus: 'eus'
  eastus2: 'eus2'
  eastus2euap: 'ecy'
  eastus3: 'eus3'
  francecentral: 'frc'
  francesouth: 'frs'
  germanynorth: 'gn'
  germanywestcentral: 'gwc'
  indiasouthcentral: 'isc'
  indonesiacentral: 'idc'
  israelcentral: 'ilc'
  israelnorthwest: 'iln'
  italynorth: 'itn'
  japaneast: 'jpe'
  japanwest: 'jpw'
  jioindiacentral: 'jic'
  jioindiawest: 'jiw'
  koreacentral: 'krc'
  koreasouth: 'krs'
  malaysiasouth: 'mys'
  malaysiawest: 'myw'
  mexicocentral: 'mxc'
  newzealandnorth: 'nzn'
  northcentralus: 'ncus'
  northeastus5: 'ne5s'
  northeurope: 'ne'
  norwayeast: 'nwe'
  norwaywest: 'nww'
  polandcentral: 'plc'
  qatarcentral: 'qac'
  saudiarabiaeast: 'sae'
  southafricanorth: 'san'
  southafricawest: 'saw'
  southcentralus: 'scus'
  southcentralus2: 'usc2'
  southeastasia: 'sea'
  southeastasia3: 'sg3'
  southeastus: 'use'
  southeastus3: 'use3'
  southeastus5: 'use5'
  southindia: 'ins'
  southwestus: 'swus'
  spaincentral: 'spc'
  swedencentral: 'sdc'
  swedensouth: 'sds'
  switzerlandnorth: 'szn'
  switzerlandwest: 'szw'
  taiwannorth: 'twn'
  taiwannorthwest: 'tnw'
  uaecentral: 'uac'
  uaenorth: 'uan'
  uksouth: 'uks'
  ukwest: 'ukw'
  westcentralus: 'wcus'
  westcentralusfre: 'wfre'
  westeurope: 'we'
  westindia: 'inw'
  westus: 'wus'
  westus2: 'wus2'
  westus3: 'wus3'
  usgovvirginia: 'ugv'
  usgovtexas: 'ugt'
  usgovarizona: 'uga'
  usdodeast: 'ude'
  usdodcentral: 'udc'
}

@export()
@description('Returns the location abbreviation for the provided location. If the abbreviation is not found, returns "unknown".')
func getShortLocation(location string) string => regionAbbreviations[toLower(location)] ?? 'unknown'


